schema_version: 1

context:
  name: segment-analytics-python
  version: 2.4.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/segment_analytics_python-${{ version }}.tar.gz
  sha256: 56184d755aa73415a59e113239f14ff0f98b3bd77b6bfea6c6034a87de561a38

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - requests >=2.7,<3
    - python-dateutil >=2.2,<3
    - pyjwt >=2.12,<3
tests:
  - python:
      imports:
        - segment.analytics
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: The hassle-free way to integrate analytics into any python application.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/segmentio/analytics-python
  repository: https://github.com/segmentio/analytics-python
  documentation: https://github.com/segmentio/analytics-python/blob/master/README.md

extra:
  recipe-maintainers:
    - thewchan
    - xylar
